# Generated by Django 6.0.4 on 2026-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='asunto',
            field=models.CharField(max_length=100, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='documento',
            field=models.CharField(max_length=50, verbose_name='Documento de identidad'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de la solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo de solicitud'),
        ),
    ]
